{"name": "Создание уже существующего пользователя", "status": "passed", "description": "Тест проверяет, что при создании уже существующего пользователя возращается ошибка 403", "start": 1729422901477, "stop": 1729422901699, "uuid": "91e434b3-4277-4359-a6df-b000e71dc42d", "historyId": "3798aeec73f27a6b274c7f46a1366005", "testCaseId": "3798aeec73f27a6b274c7f46a1366005", "fullName": "tests.test_create_user.TestCreateUser#test_create_existing_user", "labels": [{"name": "parentSuite", "value": "tests"}, {"name": "suite", "value": "test_create_user"}, {"name": "subSuite", "value": "TestCreateUser"}, {"name": "host", "value": "NikashaXD"}, {"name": "thread", "value": "7516-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "tests.test_create_user"}]}