{"name": "Логин с неверным паролем", "status": "passed", "description": "Тест проверяет, что при логине с неверным паролем возвращается ошибка 401", "start": 1729422906627, "stop": 1729422906765, "uuid": "17388fbd-1168-463e-8f83-fa1d5ddadff2", "historyId": "395623adc05914c39efc7ea003e962de", "testCaseId": "395623adc05914c39efc7ea003e962de", "fullName": "tests.test_login_user.TestLoginUser#test_login_invalid_fields", "labels": [{"name": "parentSuite", "value": "tests"}, {"name": "suite", "value": "test_login_user"}, {"name": "subSuite", "value": "TestLoginUser"}, {"name": "host", "value": "NikashaXD"}, {"name": "thread", "value": "7516-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "tests.test_login_user"}]}